# Generated by Django 6.0.6 on 2026-06-03 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(choices=[('vitoria_a', 'Vitória Time A'), ('vitoria_b', 'Vitória Time B'), ('empate', 'Empate')], max_length=20)),
                ('pontuou', models.BooleanField(blank=True, null=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='jogos.jogo')),
            ],
        ),
    ]
