# Generated by Django 6.0.6 on 2026-06-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_a', models.CharField(max_length=100)),
                ('time_b', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='agendado', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('vitoria_a', 'Vitória Time A'), ('vitoria_b', 'Vitória Time B'), ('empate', 'Empate')], max_length=20, null=True)),
            ],
        ),
    ]
