# Generated by Django 6.0.6 on 2026-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_grupo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
